platform :ios do
  before_all do |lane|
    ENV['localBuild'] = 'true'
  end

  lane :build do
    buildMode = ENV['releaseBuild'] == 'true' ? 'Release' : 'Debug'

    gradle(
      task: "assembleComposeApp#{buildMode}XCFramework"
    )

    build_app(
      project: "./iosApp/iosApp.xcodeproj",
      configuration: buildMode,
      scheme: "iosApp",
      destination: "generic/platform=iOS",
      # Disabling CodeSign and Archive so we don't need to deal with provisioning profiles
      # For real projects, do not skip these steps
      skip_codesigning: true,
      skip_archive: true
    )
  end

  lane :test do
    buildMode = ENV['releaseBuild'] == 'true' ? 'Release' : 'Debug'

    gradle(
      tasks: [
        ':composeApp:iosSimulatorArm64Test',
        ':composeApp:iosX64Test',
      ]
    )

    gradle(
      task: "assembleComposeApp#{buildMode}XCFramework"
    )

    run_tests(
      project: "./iosApp/iosApp.xcodeproj",
      configuration: "Debug",
      scheme: "iosAppUiTest",
      device: "iPhone 16 (18.2)",
      ensure_devices_found: true,
      prelaunch_simulator: true,
      fail_build: false,
      reset_simulator: true
    )
  end
end

platform :android do
  lane :build do
    gradle(
      task: "assemble",
      build_type: "Debug"
    )
  end

  lane :test do
    gradle(
      task: "testDebugUnitTest"
    )
  end
end
